language: rust
dist: xenial
addons:
  apt:
    sources:
    packages:
      # Dependencies for this package

cache: travis_wait cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - "travis_wait"
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      rustup component add clippy;
    fi'

script:
  - "travis_wait"
  - cargo test --verbose --all-features
  - "travis_wait"
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
