[package]
name = "point-derive"
version = "0.1.0"
authors = ["Chris Holcombe <christopher_holcombe@comcast.com>"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
proc-macro = true

[dev-dependencies]
storage-metrics = {path = "../"}
